name: CI Pipeline

on:
  push:
    branches:
      - main
      - gh-pages
      - Maximus-Branch
      - px's-branch
      - SongYu-branch
      - yh's-branch
  pull_request:
    branches:
      - main
      - gh-pages
      - Maximus-Branch
      - px's-branch
      - SongYu-branch
      - yh's-branch

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t sepp-nginx .
